name: React CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
   steps:
    - name: Install yarn dependencies
      run: yarn install
    - name: Start test project
      run: yarn test
    - name: Build project
      run: yarn build
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USER }}
          REMOTE_PORT: 22
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          TARGET: 


