name: React CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: asiapay.uz
        username: user
        password: O4nftq7n
        port: 22
        # script: cp -R dist/* /home/user/www/server.asiapay.uz/


