name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
        name: Check out repository
      - uses: actions/setup-node@v1
        name: Set up Node.js
        with:
          node-version: 18.x
          cache: yarn
      - run: |
          yarn install
          yarn build
          cp -R dist/* /home/user/www/server.asiapay.uz/
