name: Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - run: yarn install
        name: Install dependencies
      - run: yarn test
        name: Test project
      - run: yarn build
        name: Build project
      - run: cp -R dist/* /home/user/www/server.asiapay.uz/
        name: Deploy to server
