name: React CI/CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            git clone git@github.com:devnodir/webpack-template.git github 
            cd github
            yarn install
            yarn build
            cp -R dist/* /home/user/www/server.asiapay.uz/
            rm -rf /home/user/github
